var researchTitles = [
  "Beauty Parlor Management System",
  "Daily Time Record and Payroll System with Barcode/Biometric",
  "Budget Management System",
  "Queuing System",
  "Financial Management with SMS Notification",
  "Procurement Management System",
  "Financial Documents Archiving Management System",
  "Teller’s Queuing System Using Barcode Technology",
  "Service Marketplace System",
  "Tailor Booking Management System",
  "D Visualization of Conic Sections in XNA Game Programming Framework",
  "A D Immersive Environment for Visualising Robot Sensor Data",
  "A calibration system for a visual prosthesis",
  "A collaborative web-based genome browser for large-scale epigenomic analysis",
  "A Comparison of the Efficiency of an Atomic Component Operation versus Primitive Operations for Building a Real-Time Collaborative Editing API",
  "A covert channel based on weak memory",
  "A DSpace Mobile Theme for San Diego State University",
  "A Dynamic Database Approach for E-Commerce System Using WordPress",
  "A Flexible Test Interface and Grading Service For an AJAX Based Course Management System",
  "A Foundational model of the ARM Memory Management Unit",
  "A Household Mobile Robot",
  "A Journey through the Lattice",
  "A Method for Minimizing Computing Core Costs in Cloud Infrastructures That Host Location-Based Advertising Services",
  "A Mobile Application to Aid Consumers in Accessing Cost Effectiveness in Their Automobile",
  "A Mobile Device-Controlled Blood Pressure Monitor",
  "A Mobile Tool about Causes and Distribution of Dramatic Natural Phenomena",
  "A new Operating System Design for the Argus Multiprocessor platform",
  "A New RAID Linux Flash File System",
  "A New Software Project Management Tool",
  "A PhD Thesis Submission/Examination System for UNSW",
  "A Preferential Voting System as a Collaboration Software Solution",
  "A service oriented cross-platform approach to perform thermodynamic calculations",
  "A System for Retrograde Analysis in Chess",
  "A System for Verifying Modularity in Action Theories",
  "A System to Assist with Teaching Allocation",
  "A usability Analysis of Privacy-preserving mobile applications through crowd sourcing",
  "A Voting Ballot Web Application as a Collaborative Support System",
  "ACP Automated Course Portal through Email",
  "Adaptive Content Replication in Peer to Peer Networks",
  "Adaptive E-learning",
  "Adaptive Low Bit Rate Video Streaming Over Wireless Networks",
  "Adaptive Server Selection in Peer-to-Peer Networks",
  "Advanced File Manager with Multiple Functions to Manipulate Files with Different Formats",
  "Advertisement Management System",
  "Airline Reservation System",
  "AJAX-based Process and Service Mashup",
  "Allocation problems in practice",
  "An AJAX Based Technical Forum for Thermodynamics Community",
  "An AJAX-Based Event Calendar for a Course Management System",
  "An Alternative Data Structure to Line Sweep Algorithm",
  "An Android Application for Crime Analysis in San Diego",
  "An Efficient Location Information Management System LIMS For Smartphone Applications",
  "An Insight on a Mobile Friendly Web",
  "An Intelligent Healthcare Data Management System for Mobile Environment",
  "An Interactive Economic GIS Tool for Europe Using Map Objects for Java",
  "An Interactive GIS Tool on Chinese History and Its Topography",
  "An Interactive GUI Design for Code Analysis",
  "An Interactive History and Geography of Mexico Using Map Objects for Java",
  "An Interactive Mitochondrial Database",
  "Analysing logs of super computers and data centres for anomaly detection",
  "Analysis and Classification of Time-Series X-Ray Crystallography Image Sequences",
  "Analysis and Debugging Techniques of Android Platform",
  "Analysis of next generation sequencing data of microbial communities",
  "Analysis of Protocols for High-assurance Networks",
  "Android App for School of Arts and Design",
  "Android Application for Library Resource Access",
  "Android Based Menu Ordering App",
  "Android based processor for real-time image processing in a bionic eye implant",
  "Android Based Student Handbook",
  "Android Implementation of the mSpeed mobile application",
  "Android Joystick Application using Bluetooth",
  "Android Mobile Quiz Game",
  "Android Controlled Car",
  "Android-Based Class Attendance Monitoring Application using Barcode",
  "Answer Set Programming for Robot Control",
  "API development for Application Analysis using CLANG/LLVM",
  "Application Analysis for Designing Embedded Hardware",
  "Application Design and Measurement in Cloud Platforms",
  "Application Locker Android",
  "Application of Ant-Based Technology in Selection of Glycan Markers for Cancer Detection",
  "Application of Random Forest Algorithm in Biomarker Discovery for Cancer Detection",
  "Applying Informed Search Methods to General Single-Player Games",
  "Arabic Culture Course Management System",
  "Architecture-driven Security Analysis",
  "ASIP Design",
  "Assorted GIS Tools",
  "Attendance and Monitoring System using Barcode Technology",
  "Attendance System using Barcode Technology",
  "Automated Business Permit Issuance System",
  "Automated Code Partitioning for MPSoC Architectures",
  "Automated Legacy Code Partitioning for Embedded Systems",
  "Automated Test Generation with Static Analysis",
  "Automated Water Dispenser with Purifier with LG Touch Screen",
  "Automatic extraction of information from textual financial data",
  "Automatic IP Generation for ARGUS framework in FPGAs",
  "Automation of Android Application and Bug Tracing Mechanism",
  "Availability Analysis for Applications in Public Cloud",
  "Bacterial evolution modelling the dynamics of antibiotic resistance",
  "Belief Revision for General Game Playing",
  "Big Data Analytics Hadoop Performance Analysis",
  "Big Data Platform",
  "Big Data Provenance",
  "Bike and Running Trails on Android based on Google Maps API",
  "Billing System",
  "Bioinformatics of the immune system",
  "Bioinformatics software testing",
  "Biometric authentication on Apple Watch",
  "Biometrics Projects",
  "Bluetooth Controlled Robot using Android Mobile CoE/CpE/IT/CS",
  "Book Catalog Application using Android",
  "Breadcrumb Recommendation System The Nexus of User Intuition on Conceptual and Statistical Association",
  "Brgy Certificate Issuance and Record Management System",
  "Brgy Residents Information System PHP/MySQL",
  "Building a Web Content Management System",
  "Building Change Detection Based on Remote Sensed Images",
  "Building Provably Secure Application",
  "Burrows-Wheeler Aligner A Parallel Approach",
  "Business Permit Issuance System",
  "C-to-HDL Synthesis and Exploration for the ARGUS platform in FPGAs",
  "Camera-Based Heart Rate Detector using Android",
  "Car Registration License Plate Detection and Recognition System",
  "Cascading Style Sheet Generator",
  "Cashiering and Queuing System",
  "Causal disease mutation identification in whole genome sequencing data",
  "CEGAR testbed in Haskell",
  "Cemetery Mapping and Information System",
  "Chart feature facility packaged for map object java edition",
  "CIBER Measurement Repository",
  "Class Scheduling System",
  "Class Time Table in Android",
  "Classroom Management System",
  "Click Modular Router on seL",
  "Client server based guidance system",
  "Cloud Based File System on Mobile Device",
  "Cloud-based computing for massively parallel single-cell transcriptomic analysis",
  "Cloud-in-Cloud Software Defined Data Center for the Next Generation of Cloud Computing",
  "Co-ordinating Multiple Cognitive Robotic Agents",
  "CogenPro Migration from Java Desktop Application to Web Application",
  "Cognitive vision",
  "Collaborative Search of Universities for MS in the Southwestern US",
  "Colonial History of Mexico A Bilingual GIS Application",
  "Come and talk about topics of mutual interest",
  "Comparative Analysis of Solutions to the Ramification Problem",
  "Comparative Performance of Model checkers for epistemic logic",
  "Comparative Study of Oracle Spatial and Postgres Spatial",
  "Comparing performance of applications written in native SDK web phone frameworks and HTML",
  "Comprehensive Web Application for CITER Center of Industrial Training and Engineering Research",
  "Computer Assisted Instruction any topic/subject PHP/MySQL Moodle",
  "Computer Laboratory Time Management System",
  "Computer-Aided Instruction with Voice Recognition system",
  "Computerized Assessment of School Fees",
  "Computerized detection of lung diseases using HRCT images",
  "Computerized Faculty Evaluation System",
  "Concurrency theory and distributed systems",
  "Concurrent Programming Patterns for Scalable Network Platform Node js",
  "Configurable Low-power FFT Processor Design and Implementation for Synthetic Aperture Radar SAR Applications",
  "Content Management System for Art Lab SDSU",
  "Continuous Deployment for Big Data Analytics Applications",
  "Controlling a mobile robot using speech",
  "Conversational Agent",
  "Conversational agents for health communication",
  "Convert sdo_geometry objectS to esri shapefiles",
  "Converting American Sign Language to voice using RBFNN",
  "Coordinated Multi-Robot Security System Using Fuzzy Logic Decision Making",
  "Coordinating teams of robots",
  "Course/Program Recommendation System",
  "Creating Leon platform for ARGUS",
  "CREST and Process Mashup in the Cloud",
  "CSE Database Managing Research/Publication Data",
  "CUDA Implementation of Parallel Algorithms for Animal Noseprint Identification",
  "Customization for Mobile EBook Readers",
  "Cystic Fibrosis Patient Monitoring Application",
  "Data Parallel Haskell Benchmark Suite",
  "Data Races Detection in Java Programs",
  "Deadlock Detection and Recovery in Linux",
  "Decision support for a home telehealth system",
  "Decision Support in Recommender Systems Using Opinion-Based Reviews",
  "Decoding the language of life epigenomic determinants for cell-type-specific signalling response",
  "Deep sequencing analysis of the early infection phase of hepatitis C virus",
  "Dependable Auditing on Operations of in-Cloud Applications",
  "Dependable Cloud Operations and Systems",
  "Deployment of OpenCV for Embedded Systems and Multicore",
  "DESIGN AND ARCHITECTURE OF VISUALIZATION SERVICE IN THE CYBERINFRACTURE WEB APPLICATION FRAMEWORK",
  "Design and development of a Kinect-based D quantitative facial assessment tool for clinical practice",
  "Design and Implementation of an Automated Software Verification Tool",
  "Design and Implementation of Workflow for Content Management System",
  "Design and Implementing Web Content Management System",
  "Design of Digital Circuits for FPGA Fault Tolerance",
  "Design of Synthetic Aperture Radar SAR Application Specific Instruction Set Processor ASIP",
  "Designing a Better Authentication Model",
  "Designing Adaptive Interfaces",
  "Designing and implementing a memory-safe C language and its runtime library",
  "Designing effective instructional animations",
  "Designing Network-on-Chips for the ESLoC Platform",
  "Desktop Quiz game for HRM",
  "Detect Malodorous Software Pattern and Refactor them",
  "Detecting Exaggerated Rankings in Online Reviews",
  "Detecting software bug for Go programs",
  "Detection of referrable stage of diabetic retinopathy in new retinal camera images",
  "Determining Dolphin Species by Their Echolocation Clicks A Study of the Effects of Site Variability Noise And Recording Equipment Differences",
  "Developing Google Android Application Using the RESTful Web-Services",
  "Developing Google Android Mobile Clients for Web Services",
  "Developing new methods for analysis of next generation genome sequencing data",
  "Development of Json and Ajax enabled database driven user interfaces for science application portals",
  "Dictionary Program PHP/MySQL Android",
  "DLOOP A Flash Translation Layer Exploiting Intra-plane Copy-back Operations",
  "Document Reader Interface Database and Admin Panel",
  "Document Reader Interface Designing the GUI",
  "Domain Specific Modelling Language Design for Model Driven Development",
  "Drowsy and Decay Leakage Control for the Register File/Cache Memory Architecture",
  "DTR Daily Time Record System",
  "DTR Daily Time Record System with Biometrics",
  "Dynamic program analysis for bug detection using static program slicing",
  "Dynamic Projection of Data on Maps Based on Time-lines Client Side",
  "E-commerce paypal integration",
  "E-Learning System",
  "E-voting system",
  "E-Voting System with SMS technology",
  "Ecommerce site â€“ PHP/MySQL Joomla Wordpress",
  "EDSL for data serialisation and de-serialisation",
  "EDSL for mobile graphic apps",
  "Educational Android Quiz game for Computer Fundamentals - Android",
  "Effective Cross-Kernel Communication",
  "Electronic Ordering System",
  "Electronic Police Clearance System",
  "Email based FAQ web application",
  "Embedded algorithms for a low power wearable fall detector",
  "Employee Ranking System",
  "Encultured Agents for teaching culture",
  "Enhanced AutoCAD Grading Application Back End Component",
  "Enhanced AUTOCAD Grading Application Front End Component",
  "Enhanced Mapping Application for SDSU Study Abroad Program",
  "Enhancement of MC Simulator Macros to Support Floating Point Number",
  "Enhancing the Autonomous Robotic Person Detection and Following Using Modified Hough Transform",
  "Enrollment System PHP/MySQL",
  "Entrance Examination",
  "Evaluation of Expert Diagnosis for Lung Diseases",
  "Evaluation of Heterogeneous Communication Architecture for MPSoCs in ARGUS",
  "Evaluation of Mapping Techniques for Heterogeneous MPSoCs for ARGUS",
  "Evaluation System Faculty & Staff",
  "Event Planner with SMS and Social Sharer Android",
  "Evolution of Cricket and Comparison to Baseball",
  "Evolution of Democracy in Europe",
  "Evolution of EGF domains",
  "Evolution of Redox-regulation of Cys Residues in Proteins",
  "Evolution of transglutaminases from papain-like cysteine proteases",
  "Examination Scheduler",
  "Execution Monitoring for Robots",
  "Exploiting the weakest link in high-security systems",
  "Exploring Structural Properties and Consensus Performance in Complex Networks",
  "Exploring the genotype/phenotype relationships in lamin A/C",
  "Expressiveness of Distributed Systems",
  "Face Detections",
  "Face Recognition System",
  "Facilitating Research with Learner Data in Online Speaking Test",
  "Faculty Annual Report Maintenance Website",
  "Faculty Information System",
  "Fault Tolerance Platforms for Large-Scale Distributed Applications",
  "Fault Tolerant Token Ring Network Design for SEU Recovery on Reconfigurable Hardware",
  "Field Testing and Performance Evaluation of a Mobile-Platform-Based QR Code Reader for Multilingual Public Information Display Applications",
  "Fine Grained Location Using Mobile Augmented Reality",
  "Finger Position Data Acquisition System for Cross-Modal Tactile/Visual Cognition Studies",
  "Fire and Smoke System with SMS notification",
  "First person view system for a remote control aircraft",
  "First-aid App for Android",
  "Fish Information System",
  "Fleet Monitoring via GPS GPRS/GSM using Huawei Modem",
  "Flood Monitoring with GPRS TEch using Google Earth API",
  "Formal modelling verification and analysis of wireless mesh networks",
  "FPGA implementation of ASIP Processors",
  "FPGA-based satellite flight computer",
  "Functional verification of dynamic reconfiguration in Zynq FPGAs",
  "Game AI Believeable Characters",
  "Game AI Conversational behaviours",
  "Game Design Game Feel",
  "Game design Games for Vision Science",
  "Game Design Procedural Level Generation",
  "Game Design Project",
  "Game interfaces Cognitive load adjustment",
  "Gene regulatory network in embryonic organ development",
  "General Game Playing for Security Games",
  "General Game-Playing Robot",
  "General Service Office Automated Inventory System",
  "Generating Data for Relational Schemas",
  "Generating Game-Specific Knowledge to Improve Monte Carlo Tree Search",
  "Generation and Analysis of Finite Monoids with an Emphasis on Syntactic Monoids",
  "Generic Log Analysis Tool",
  "GENERIC TOPIC Programming Languages & Systems",
  "Genome based molecular typing of pathogenic bacteria",
  "Genome-wide chromatin landscape analysis of fungal epigenomes",
  "Geographic Information System with Flood-Prone Location",
  "Geolocation Project Google Gears API",
  "Geospatial Information Extraction from Big Data Streams",
  "Get Help Android App with GPS and Map",
  "GIS application on modern Mexico",
  "GIS Assisted History of Middle East Empires",
  "GIS Based Application Tool History of East India Company",
  "GIS Based Learning Tool for World's Largest Earthquakes and Its Cause",
  "GIS based tool on Indian Independence Movement",
  "GIS Learning Tool for Ottoman Empire",
  "GIS Learning Tool for USA's Tallest Skyscrapers and Their Construction",
  "GIS Multimedia Teaching Tool about Africa",
  "GIS Multimedia Teaching Tool about the Mormon Battalion",
  "GIS Multimedia View of Local Politics",
  "GIS Tool for California State Legislature Electoral History",
  "GIS Tool for Chinese Diaspora",
  "GIS Tool for Learning about Ottoman Empire",
  "GIS Tool for Learning about Russian Empire",
  "GIS Tool for US Possessions",
  "GIS Tool on Fuel Resources of the American Continent",
  "GIS Tool Showing Emperors Wars and Important Battles During the Rise and Fall of Roman Empire",
  "GIS Tool to Demonstrate Freeway Evolution in San Diego",
  "GIS Tool to Locate Sikh Temples in US",
  "GIS Tri-Lingual Tool for Learning about South and Central America",
  "GIS-based Interactive Tool to Map the Advent of World Conquerors",
  "GIS-Based Seismic Damage Assessment",
  "GPS Tracking System",
  "Grade Viewer Application in Android",
  "Grading System /MySQL",
  "Grid Navigation & Path Planning Algorithm Using a Proposed New Greedy Approach",
  "Group Messenger Application using Android",
  "GSR Sensor with Android App",
  "Hardware design for Power Anlaysis Attacks in Embedded Systems",
  "Hardware development on the ESLoC Multiprocessor Platform",
  "Hardware interconnect development for Modern Caches and Processors",
  "Herbal Plants Information System",
  "High School Grade Recording System Form & Form",
  "High-Level Control Programs for Baxter Robot",
  "Highly Interactive Web Services",
  "Holistic Computerized Faculty Evaluation System",
  "Home Appliances controlled by Android Smartphone",
  "Hospital system",
  "Hotel and Reservation System PHP/MySQL",
  "Hotel management system",
  "Hotel Reservation Application with Mobile Compatibility in Android",
  "Hotel reservation system",
  "Human Resource Information System HRIS",
  "Human Resource Management System",
  "Iberian Exploration Seen Through GIS",
  "Identification and resolution of issues in systems security",
  "Identification of Alternative Translation Initiation Sites Bioinformatic Analysis of Mammalian ' UTR Location Prediction of Start Sites",
  "IGP Billing System",
  "Image Edge Detection Using Ant Colony Optimization Algorithm",
  "Implementation of DTW Algorithm for Application Security",
  "Implementation of Identity Discovery as a Service Provided By Third Party Authentication Server",
  "Implementation of Strong Invariance on ACO Algorithms And Optimized Routing of Data Packets in Wired Networks",
  "Implementing processor cores on FPGAs",
  "Importance of Metadata in Data Warehousing",
  "Improved User Interface to Display and Edit Multiple Files and Folders",
  "Incredible India GIS Based Application Tool",
  "Incremental program analysis for software testing",
  "Indoor Mapping and Localisation with Google Tango",
  "Information Extraction from Seminar Notices",
  "Information flow analysis for mobile applications",
  "Integration of Simplescalar and McPAT for Multiprocessor platforms",
  "Integrative analysis of histone-modifying enzymes' expression program",
  "Intelligent Indoor Localisation and Navigation with Smart Glass",
  "Intelligent Object Recognition in Smart Glass",
  "Intelligent Traveler Locator using Google Map Application",
  "Interactive Graphical Interface for Printed Glycan Array Data Analysis",
  "Interactive Spelling Game Android",
  "Interactive World Map Man Made Disasters",
  "Interactive World Map Natural Disasters",
  "Internet Cafe System",
  "Interpreting a formal security protocol language in an epistemic model checker",
  "Interrupt-Related Covert Channels on seL",
  "Investigating the Use of Microsoft Kinect D Imaging for Robotic Person Following",
  "iPad app for cardiopulmonary resusciation",
  "iPhone Application Development",
  "Job Recommendation Algorithms",
  "JPEG to STL Translation Software for Color/Texture Mapping in Support of D Printing of Surfaces Used in Visual/Tactile Cross-Modal Cognitive Neuroscience Research",
  "K-Means Clustering with Automatic Determination of K Using a Multi-Objective Genetic Algorithm with Applications to Microarray Gene Expression Data",
  "Kinect Mouse with Voice Recognition",
  "Knowledge Based Analysis of a Distributed Protocol",
  "Lan-based Computer Games for Fisheries",
  "Language Support for GPU Programming",
  "LARC Resources LIB",
  "Lazada Like App for Android",
  "Leaderless Byzantine Paxos",
  "Learning Languages from archival material",
  "Lending Management system",
  "Library and Computer Time Usage System",
  "library system",
  "Library System PHP/MySQL",
  "Literature review on formal modelling and verification for embedded medical systems",
  "LLVM Compiler for Novel Processor",
  "Loaning System",
  "Online E-Learning System",
  "Online Examination System", 
  "OJT Timesheet Monitoring System",
  "Home Surveillance and Automation",
  "iPhone SMS Notification Systems", 
   "Using GSM Technologies for Detecting Theft",
  "POS Apps and Their Use",
  "Business Use Cases for Accounting Apps", 
   "Time Tracking Solutions for Office Productivity",
   "SMS Doorbell Notification Tools",
   "Wireless Technologies for Surveillance", 
  "Online Learning Systems and Their Relevance",
  "Online Apps For Business Management",
  "Improving Nursing Education With a Healthcare System", 
  "Project Management Tracking Systems",
  "Biometric Security Systems",
  "Most Important Tools For Managing Data Security", 
  "Most Important Tools For Managing Data Security",
  "How The Internet Works: The Basics",
  "Introduction to Data Mining", 
  "Emergency Vehicle Notification Systems",
  "Benefits of Data Mining",
  "Student Tracking Performance", 
  "Library Information System",
  "Student Information System",
  "Student Handbook Application", 
  "Thesis and Capstone Archiving System",
  "School Portal Application",
  "School Events Attendance System", 
  "Grading System",
  "Student Profile and Guidance Services with Decision Support",
  "Faculty Evaluation System", 
  "Online School Documents Processing with Payment System",
  "Class Scheduling System",
  "Student Council Voting System", 
  "Android Based E-learning",
  "OJT Records Monitoring System",
  "Sales and Inventory System", 
  "Point of Sale Application",
  "Boarding House Management System",
  "COOP Management System", 
  "Insurance Management System",
  "Local Points of Interest Using Augmented Reality",
  "Local Search Techniques for General Single-Player Games",
  "Location Based Chat Application for iPhone",
  "Location Based Computerized Multimedia Presentation of Theodore Roosevelt's Life History",
  "Location Based Interactive Learning Tool on Life History of Midge Costanza",
  "Lower bounds for extremal vertex sets in graphs",
  "Making a Flash Translation Layer Reliability-Aware An Optimized Strategy for Wear-Leveling and Garbage-Collection",
  "Managing Risk in using Cloud Services",
  "Many-core simulator implementation",
  "Map Based Multimedia Tool on Pacific Theatre in World War II",
  "Map Based Teacher Credentialing in the United States Client Side",
  "Map Based Teacher Credentialing in the United StatesServer Side",
  "Mapping Application for LARC Study Abroad Program",
  "Mapping Engine to calculate trends in chatter in social media",
  "Mapping of Zn fingers in the brain",
  "Matching Algorithms for Recommendation in Online Dating",
  "Matching Words and Pictures Cross-modal Multimedia Web Infomation Aggregation",
  "Math Games",
  "Math Games for Algebra",
  "Measure and Conquer for Efficient Edge Domination",
  "Media Asset Database for SDSU School of Art Design and Art History",
  "Medical and Dental Record Management System",
  "Medical and Laboratory Record Keeping System PHP/MySQL",
  "Medical records system",
  "Medicine Inventory and Patient Information system",
  "Message-passing vs migrating threads",
  "Mobile Application for Business Card Capture",
  "Mobile desktop PC Remote",
  "Mobile Educational Application for Elementary Student using Android",
  "Mobile Friendly Web App for CS Department",
  "Mobile Health Tips using Android",
  "Mobile inventory",
  "Mobile PDF Conversion Application for the Android Platform",
  "Mobile Pharmacy Application in Android",
  "Mobile Point-Of-Sale Application with SMS Notification",
  "Mobile Real Estate Agent for Android",
  "Mobile Real Estate Agent for iPhone",
  "Mobile Reservation for Banquet Halls",
  "Mobile Store Management System",
  "Mobile Ticketing via SMS gateway using Clickatell",
  "Mobile Voting",
  "Mobile Voting System using Android",
  "Model Checking Tool Suite for Protocol Development",
  "Modelling and Analysing Financial Market Datasets",
  "Modelling and Manipulating Genealogical Data",
  "Modelling Network Routing Protocols",
  "Molecular mimicry in viruses and cancer",
  "Motorcycle Tracking with GPS using Android",
  "Movement detection with SMS Alert IP cam CCTV",
  "Multi-core Automated Software Verification",
  "Multi-valued Decision Diagram Package",
  "Multicore Embedded System Design for Space Applications",
  "Multimedia Survey Of Colonial India",
  "NeevEngine Using XNA Game Studio for Serious Game Design and Development",
  "New Measurement Techniques for a Science of Networks",
  "NewsMap On The Go",
  "Noteworthy Scientists and Inventors An Interactive Learning Tool",
  "On customization of Embedded Processor Systems",
  "On degrees of nondeterminism in finite automata and related concepts",
  "On Memroy Data Protection for Embedded Processor Systems",
  "On Modeling Emergent Neocortical Complexity with Complex Adaptive Systems",
  "On Route Travel Assistant for Public Transport Based on Android Technology",
  "On the potential of big Advertisement players in the ads targeting business",
  "On-chip networks for reconfigurable and many-core computing",
  "On-line courseware",
  "On-line Exercises for WebCMS",
  "Online Alumni Information System - PHP/MySQL Joomla",
  "Online bidding system",
  "Online billing system",
  "Online class scheduling system",
  "Online Financial Independence Score",
  "Online Grade Inquiry",
  "Online Grading System",
  "Online hotel reservation system",
  "Online inventory system",
  "Online Lot Reservation",
  "Online management system",
  "Online membership and billing system",
  "Online ordering system",
  "Online payroll system",
  "Online Portal for San Diego County",
  "Online POS Point of Sale",
  "Online Product Reservation System",
  "Online public access catalog",
  "Online Reservation",
  "Online Shopping Cart",
  "Online Tracking Google Map",
  "Online voting system",
  "OpenCL backend for Accelerate",
  "Optimization of Multi-view Video Coding MVC",
  "Order Billing Inventory System",
  "Parallel Computation of Functions on Set Partitions",
  "Parallel Programming on a GPU Using Intel Array Building Blocks",
  "Parameterized Algorithm for k-Leaf Spanning Tree",
  "Parameterized Algorithms for Backdoor Detection",
  "PARE A Partial Replication Strategy Adaptive to Movie Popularity Changes for Video-on-Demand Servers",
  "Parish Record Keeping System",
  "Parking Lot system RFID",
  "Path Planning in Planar Environments using Triangulations",
  "Patient Record System with Decision Support",
  "Payment Checkout System for Online Testing Tool CAST",
  "Payroll system",
  "Payroll System with Biometric and Barcode Technology",
  "Payroll System",
  "PE Tools Management System",
  "People to People Recommendation in Social Networks",
  "Performance Evaluation of Reconfigurable Control Network",
  "Performance profiling of scientific simulation programs on heterogeneous systems",
  "Pharmacy Automation System",
  "Pharmacy Management System",
  "Picture Guessing Game",
  "Picture Guessing Game",
  "Plant Leaf Recognition and Matching with MATLAB",
  "Platform Independent Experimentation Workbench for Unimodal/Cross-Modal Priming Studies",
  "Polling System",
  "POS and Inventory System Version Version",
  "Post-Secondary Indian Isolation Selection Tool",
  "PPP Parallel Parity Processing Based on Multiple Parity Channels",
  "Precise and efficient pointer analysis for Javascript programs",
  "Privacy threats in online social networks",
  "Privacy-Aware Smart-Grid Monitoring",
  "Privacy-preserving cloud services for Internet of Things",
  "Privacy-Preserving Mobile Data Processing",
  "Privacy-Preserving Recommendations Systems Are users' choices biased by the recommendations systems themselves The chicken or the Egg problem",
  "Pro Bono Law Resource Centre Database",
  "Process and Service Mashup on Mobile Platform",
  "Processor Prototyping for Automobile Application",
  "Product Tracker Android App with Map",
  "Product Tracker with Google Map Android",
  "Production Line Modeling A Simplified Approach Based on Theory of Constraints",
  "Professor Pages Easy Course Website Maintenance",
  "Protected-Mode eChronos",
  "QB satellite payload implementation",
  "Quantitative Risk Management Methods in Software and Systems Projects",
  "Qubes on seL",
  "Quiz Application using Android",
  "Rapid Decision Tool to Predict Earthquake Destruction in Sumatra Using First Motion Survey",
  "Rater Notification System for Computerized Assisted Screening Tool",
  "Re-architecting WebCMS",
  "Real-time abnormal activity detection in surveillance systems",
  "Real-time suspects detection in video surveillance systems",
  "Reasoning About Actions in Imperfect-Information Games",
  "Recognising Lung features in HRCT",
  "Reconfigurable Computing Literature Survey",
  "Record management system",
  "Registrar System",
  "Registration and Synchronized Visualization of Multi-Modal D Magnetic Resonance Images",
  "Religions in the Middle East",
  "Report Generator & Server Database",
  "Research Portal Builder",
  "Resilient and Reliable Distributed Systems",
  "Resort Management System",
  "Resource Allocation Framework",
  "RFID DTR System",
  "RFID-Based Student Monitoring System",
  "Rice Sales and Inventory System",
  "RNA-seq with different read length",
  "Road traffic estimation via wireless communication",
  "RoboCup Standard League",
  "Robot Learning",
  "Robot Soccer",
  "Robotic Person Following in a Crowd Using Infrared and Vision Sensors",
  "Robots for Urban Search and Rescue",
  "Robust CSV to ShapeFile Utility and DBF File Interpreter",
  "Robust Recommender Systems",
  "Runtime Mapping of Tasks for the ARGUS Multicore Platform",
  "Safety Notification Broadcast System",
  "Sales and Inventory Monitoring System with SMS",
  "Salon System",
  "School Event Attendance Monitoring System with Biometric and Barcode Technology",
  "School Locator using Android",
  "School Management System Enrollment Registrar Cashiering Student Information Module",
  "Science Games Android",
  "SDSU Dining An Android Mobile Application Solution for SDSU Dining Services",
  "SDSU Ebuddy",
  "SDSU Goggles Android Based Application",
  "SDSUHood",
  "Secure network OS for SDN",
  "Secure terminal on seL",
  "Security Analysis of Multicore Systems",
  "Security Vulnerabilities in PHP Applications",
  "seL AUTOSAR",
  "seL-based Distributed Capability Systems",
  "Semantic Mapping with Mobile Robots",
  "Sensor networks with nano fibre",
  "Shared resources in an seL-based OS",
  "Shortest path calculation for public transport planning",
  "Simple Tools to Convert Oracle Spatial Tables to ESRI Shape Files",
  "Simulated bionic vision using a Kinect system for depth mapping",
  "Sloth vs eChronos",
  "Smart Home",
  "SMART Vendo Loading Machine",
  "Smartphone and Android Internals",
  "Smartphone app for activity classification and fall detection",
  "SMS billing- Payment using Smartmoney",
  "SMS Grading System Globe Labs",
  "SMS Marketing Software Bulk sending- email to SMS",
  "SMS-Based Grade Inquiry System",
  "SNOMED-based Surgical Audit tool",
  "Social network analysis of viral infections in prison settings",
  "Social networking",
  "Social Networking System - PHP/MySQL Joomla",
  "Soft Error Testing with Deploying Processors in Space",
  "Software for computing graph parameters",
  "Software tool for code partitioning using LLVM/CLANG",
  "Software update and implementation of multiprocessor simulation in sim-cache",
  "Solving General Single-Player Games with Constraint Programming",
  "Solving Inverse Kinematics Problems by Decomposition Classification and Simple Modeling",
  "Solving Inverse Problems by Decomposition Classification and Simple Modeling Extension to Ill-conditioned Cases",
  "Solving the Course Scheduling Problem",
  "Southern Area International Languages Network SITE SAILN",
  "Space Based Tracking of Aircraft on CubeSats",
  "SSG Management System with SMS Notification",
  "Stability of matchings",
  "Static and dynamic analysis for finding bugs in Javascript programs",
  "Static and dynamic data races detection for C/C++ programs",
  "Stochastic Computing for Fault Tolerant Systems",
  "Student Account and Cashiering System",
  "Student Assessment System",
  "Student Attendance Monitoring System w/ SMS Alert using GSM modem",
  "Student Information System",
  "Student Montiring using Fingerprint with SMS alert to parents/Guardian using Digital Persona",
  "Student Profiling in Guidance Office PHP/MySQL",
  "Super Mario Galaxy problem",
  "Supply inventory system",
  "Symbolic execution for detecting system bugs on binary code",
  "Syncing Text with the Audio for Media Access",
  "Tablet-based Control Interface for Distributed Systems Deployment",
  "Talking to Robots",
  "Teacher Credentialing in California",
  "Telehealth architecture for Android platform using HTML",
  "TeleHealth Nexus between Wireless Health Network and Biometric Data",
  "Tellerâ€™s Queuing System using Barcode Technology",
  "Tellerâ€™s Queuing System using Barcode Technology",
  "Testpad a Mobile Based Performance Assessment Tool for Language Learners",
  "Text Classification using Machine Learning",
  "The effect of antigen presentation on the T cell mediated immune response",
  "The Overlapping Variation Method Algorithm",
  "The potential of Recommender Systems to breach user privacy in PP",
  "The Real Time Interactive Interface for Spatial Economic Modeling",
  "The Singing Bee",
  "The Singing Bee with Voice Recognition Android",
  "Theorem Proving for General Game Playing",
  "Thesis Archiving System",
  "Third party tracking in mobile environment",
  "Time line help package for map objects",
  "Timed Process Algebra for Wireless Mesh Networks",
  "TimeLine Feature Package for MapObjects Java Edition",
  "Touch-Screen Based Point-Of-Sale System POS",
  "Tourist Guide Android",
  "Traffic APrking Management PDA based using Windows Mobile",
  "Traffic Guide Android",
  "Twitter Data Analysis",
  "US Senator Election History An Android Application",
  "Understanding and Improving Operational Processes in Large-scale Distributed Systems",
  "UNSW Course Advisor",
  "US House Electoral Data- GIS Based Application Tool",
  "Usability Testing of Android Applications",
  "Use of next generation sequencing to analyse genome evolution in infectious and genetic diseases",
  "Using GPUs to solve challenging optimization problem",
  "Using Machine Learning to Model Connections between Poli tical Competition and International Conflict",
  "Using Speech to Play Games",
  "Vendo Pharma / Prescribing Machine / /-",
  "Vendo Projects",
  "Verification framework for concurrent C programs",
  "Verification of Secure Transaction Protocols",
  "Verifying concurrent programs running on a real-time OS",
  "Veterinary Clinic and Pet Shop Management System",
  "Video Library Management System",
  "Video Rental Application in Android",
  "Video Upload Tool with Subtitling Feature",
  "Virtual Bulletin Board for Off-Campus Housing",
  "Vision Based Robotic Person Following Using an Improved Image Segmentation Approach",
  "Visitor Log Monitoring System",
  "Visualization of the Deformation of Planet Due to Tidal Forces Using XNA Programming Framework",
  "Voice Command with bluetooth using Direct Object Speech library",
  "Voice Revolution Anrdoid Game",
  "Voice Search for Locations using Google Maps",
  "Voting System",
  "Voting System with Mobile Application",
  "Water Billing System PHP/MySQL",
  "Weather Forecast Application using Android",
  "Weather tracking System Powered by Google Earth APIs and Davis Weather Instruments",
  "Web Application Development for San Diego Cricket Club",
  "Web Content Management System for Wildland Urban Interface Fires Research",
  "Web Page Analysis",
  "Web Services Security Analysis and Management Tool",
  "Web-Based Geographic Information Support System for International Student Tutor-Mentor Program",
  "WEB-BASED TRACKING SYSTEM",
  "Website for Freeway Evolution in San Diego County",
  "Weight Build-Up & LOPA Sketch-Up Optimization Tool",
  "When & how to use gestures Connecting our bodies & minds to computers",
  "When and how to use animation Connecting human minds to computers",
  "Wiki Contributions to Software Engineering",
  "Wireless network coding extension for IEEE",
  "Wireless Projects",
  "World History Maps A GIS Based Teaching Tool",
  "XPENSTRAK Expense Tracker Mobile Application for iPhone",
  "YouTube and Beyond Exploring the unknown",
  "RFID-based Attendance Monitoring with SMS Notification System",
  "RFID Enabled Passport Verification using C#.net",
  "RFID Based Animal Identification System",
  "GIS Based Rural Development Planning using QGIS",
  "Cashless Automation System using RFID Based Prepaid Card",
  "Visitorâ€™s Log Monitoring System using RFID",
  "GIS Based Crime Incident Report",
  "GIS Based Information System for Flood Prone Area",
  "GIS Based System to Locate the most suitable areas for planting watermelon",
  "Library Automation Project using RFID",
  "GIS in Precision Agriculture",
  "GIS Based Information System for Construction Management using QGIS",
  "Android Based Attendance Management App",
  "Mobile Based Expense Manager App",
  "Android Based Civil Service Reviewer App",
  "Feedback/Comment System in Android",
  "Fitness and Exercise guide App",
  "Android Controlled Automobile using Arduino",
  "Android Based Voice Operated Home Appliance Control System",
  "Book Catalog Application using Android",
  "Android based Barangay Certification Verification App using PDF",
  "Mobile Based Event Reminder",
  "Mobile Based CCTV Remote Monitoring App",
  "Android Based Controlled Door Security Locking App",
  "School Events Notification and Reminder App",
  "Mobile Based Tuition Fee Payment App using Dragon Pay",
  "Android Based Unit Converter",
  "Mother Tongue Dictionary App",
  "Offline Elearning in Chemistry App",
  "Mobile Based Temperature Monitoring App",
  "Android Based Common Ailment Remedy App",
  "Android Based Herbal Plant Information App",
  "Android Based LPG Leakage Detection and Monitoring System",
  "Mobile Based Social Networking App",
  "PetDroid: Android Based Exercise App with Pet Buddy",
  "Design and Implementation of Doctor-Patient Interaction System Based On Android",
  "Android Based Year Book App",
  "Mobile Based Clinic Consultation App",
  "Mobile Based Face Recognition App for Attendance and Monitoring System",
  "Android Based Payment System Using QR Code",
  "Advanced GPS Location Finder To Identify Hospital Location and ATM Location",
  "Philippine History App with Admin Panel",
  "Android Based Lending/Borrowing of Library Resources",
  "FratAppMobi: Mobile Based Social Networking App for Fraternities and Sororites",
  "Android Based Electricity/Water Bill Payment App",
  "Mobile Based Personal Portfolio App available in iOS, Android and Windows Mobile",
  "Mobile app Hotel Reservation System with SMS Notification using iTexMo API",
  "Android Based Time Management System for Employers through Finger Print Authentication and Location Geo-fencing",
  "Location Based Reminder Notification App in Android",
  "Electronic Notice Board System Remotely Controlled by Mobile Devices",
  "Bike and Running Trails on Android based on Google Maps API",
  "Mobile Based Reviewer for LET",
  "Mobile Based Real Estate Property Management App",
  "Android Based Tourism App with Live Feed Viewing of Activities",
  "Android Based Pageant Tabulation App",
  "English and Spelling Learning App in Android for Kinder Students",
  "ALAK: Android based Learning App for Kids",
  "Android Based Crime Reporting App",
  "Business Terminology Dictionary App",
  "Android Based Library Book Locator",
  "Location Based Friend Finder with SOS Alert Feature",
  "Android Based Event Planner with SMS and Social Sharer",
  "Your Voice Sounds Familiar â€“ Guess the singer app",
  "Android Based eCart for Cooperative with Admin Panel",
  "Mobile Based Weather Forecast Application using Open Weather Map API",
  "JRDroid: mobile application for Jose Rizal",
  "Video Conferencing App in Android/iOS/Windows using Apache Cordova",
  "Android-Based Class Attendance Monitoring Application using Barcode",
  "Restaurant Locator using Zomato API",
  "Health Care Information Systemusing Wearable Devices",
  "Interactive Museum App with Virtual Reality",
  "Mobile Based ePrescribing App with Admin Panel",
  "Automatic School Gate Opener using RFID Reader",
  "Home Appliances Controller using Arduino",
  "Flood Alarm System with SMS using Arduino",
  "Arduino Based Vehicle Parking Counter with Web Based Console",
  "Door Opener using Fingerprint with SMS",
  "GSM Based Home Security Alarm System Using Arduino",
  "Door Lock using Magnetic Stripe Reader with Fingerprint Scanner",
  "Gas Leakage Detector with GSM Module for SMS Alert and Sound Alarm",
  "Arduino Based Home Automation",
  "Light Control System using Arduino with Mobile Support",
  "Arduino Night Security Alarm With PIR Sensor",
  "Arduino Based Electrical Appliances Control using IR",
  "Automatic Water Tank on and off System using Arduino",
  "Motion Detector using Arduino with SMS Notification",
  "Home appliances controlled by android phone using Arduino",
  "Automatic Plant Irrigation and Monitoring System",
  "Door opener using RFID with SMS",
  "Arduino Based Digital Temperature Sensor",
  "Fire alarm System using Arduino with SMS",
  "Smoke Detector Project with SMS using MQ- Gas Sensor",
  "Android Based Water Level Controller",
  "Coin Operated Car Wash System with Income Collection Report",
  "Arduino Based Distance Sensor",
  "Air Quality Monitoring System on Arduino Microcontroller",
  "Arduino Based Mosquito Repellant System",
  "Arduino Based Traffic Lights Control System with Android App",
  "SMS Based Electronic Bulletin Board using Arduino",
  "Android Based IQ Test App with Score Monitoring",
  "Android Based Geographic Information System about Disaster Prone Location",
  "IoT (internet of things): Smart Store using Arduino microcontroller",
  "Web-based Construction Project Management System",
  "Online Complaint Management and Evaluation System",
  "Web and Mobile Based School Publication System with Forum",
  "Web Based DTR and Payroll System with Android and SMS notification for Employees",
  "Web Based Agricultural Information System",
  "Web and Mobile Based Elearning System for K with Student Performance Monitoring and Evaluation",
  "Online Clinical and Administrative Health information Systems",
  "Web and Mobile Based Auction Application",
  "Online Health Management Information System and Data Warehouse using CodeIgniter and PostgreSQL",
  "Online Project Tracking and Monitoring System with Mobile App Support and SMS Notification",
  "Assistive Application for Children with Visual Hearing",
  "Web Based Medical Expert System using NodeJS",
  "Web Based Student Performance System for K-",
  "Web and Mobile Based Test Banking System with Item Analysis using PHP, MySQL and Framework",
  "Online Parish Record Keeping System (Baptismal, Marriage Contract)",
  "Online Enterprise Level System Information Management using PHP, MySQL and Material Design",
  "Online Consumer Health Informatics using PHP and MySQL",
  "Web Based Elearning Management System with Speech Recognition",
  "Web and Mobile Green House Management System",
  "Online Faculty Information and Evaluation and Ranking System",
  "Web and Mobile Food Ordering and Delivery System",
  "Web and Mobile Based Entrance Examination with SMS Notification using Twilio",
  "Web Based Asset Management System using PHP, MySQL and MaterialCSS",
  "Web-based Crime Analysis Toolkit",
  "Online School Facilities Inventory and Monitoring System with Barcode",
  "Web Based Outpatient Department Scheduling System",
  "Web Based eCrime File Management System",
  "Web Based E-Logistics For Warehouse Management with Mobile App Support",
  "Online Based Cemetery Mapping System using PHP and MySQL",
  "Web Based Ecommerce System using Dragon Pay Gateway Payment System.",
  "Online Grade Query with SMS and Mobile Support App (iOS, Android, Windows)",
  "Online Banking System with Mobile App Support",
  "Online Kindergarten Learning Courseware",
  "Online Registrar Grade Profiling and TOR Generator System with Faculty Loading and Online Grade Viewing",
  "Online Record Archiving of Soil Analysis Results",
  "Web Based E-Memo for Employees with SMS and Mobile Support",
  "Online Document Tracking System using QR Code",
  "Web Based Time Monitoring System using NFC Smart Card Reader",
  "Web Based Language Teaching Program",
  "Online Accounting and Ledger System using PHP, MySQL and Bootstrap",
  "Customer Relationship Management (CRM) using Microsoft Dynamics",
  "Online Business Franchising inventory and Monitoring System",
  "Web and Mobile Speech-assisted Automated Attendant Systems",
  "Arduino Intelligent Fire Sprinkler System with Web and Mobile Support",
  "Web Based Financial Forecasting and Planning Application",
  "Airline Reservation System",
  "Android â€“ Controlled Car",
  "Android Joystick Application using Bluetooth",
  "Android-Based Class Attendance Monitoring Application using Barcode",
  "Bluetooth Controlled Robot using Android Mobile (CoE/CPE/IT/CS)",
  "Book Catalog Application using Android",
  "Camera-Based Heart Rate Detector using Android",
  "Cemetery Mapping and Information System",
  "Centralized Medical System using Different Sensor for Vital signs Detector",
  "Class Time Table in Android",
  "Client-server based guidance system",
  "Computer-Aided Instruction with Voice Recognition system",
  "E-Learning System",
  "Electronic Police Clearance System",
  "E-voting system",
  "E-Voting System with SMS technology",
  "Face Recognition System",
  "Fish Counting System",
  "Geographic Information System with Flood-Prone Location",
  "Grade Viewer Application in Android",
  "Group Messenger Application using Android",
  "Holistic Computerized Faculty Evaluation System",
  "Home Appliances controlled by Android Smartphone",
  "Hospital system",
  "Hotel management system",
  "Hotel Reservation Application with Mobile Compatibility in Android",
  "Hotel reservation system",
  "Human Resource Management System",
  "Intelligent Traveler Locator using Google Map Application",
  "Internet Cafe System",
  "Judging System",
  "Lending Management system",
  "library system",
  "Medical records system",
  "Medicine Inventory and Patient Information system",
  "Mobile Educational Application for Elementary Student using Android",
  "Mobile Health Tips using Android",
  "Mobile Pharmacy Application in Android",
  "Mobile Point-Of-Sale Application with SMS Notification",
  "Mobile Reservation for Banquet Halls",
  "Mobile Voting System using Android",
  "Motorcycle Tracking with GPS using Android",
  "On Route Travel Assistant for Public Transport Based on Android Technology",
  "Online bidding system",
  "An online class scheduling system",
  "Online courseware",
  "Online Grade Inquiry",
  "Online Grading System",
  "The online hotel reservation system",
  "Online inventory system",
  "Expense Tracking and Monitoring System",
  "Loan Transaction and Reservation with SMS",
  "Accounting Information Management System",
  "Food Order and Catering Services System",
  "Online and SMS Based Salary Notification",
  "Pharmacy Stocks Management",
  "Laundry Booking System",
  "Hotel Reservation Application",
  "Tourism Management Database System",
  "Management Information Systems for Tourism and Hospitality",
  "Hotel And Restaurant Management And Monitoring System with SMS Support",
  "Mobile Based Tourist Destination Information",
  "Hotel Best Prices Mobile Application",
  "Hospitality Information System",
  "Cloud-Based Property and Hospitality Management",
  "Hotel Booking App For Smart Travel",
  "Point of Sale (PoS) System used in the Hotel Industry",
  "BrowseHotel: Hotel Hopping using Mobile Devices", 
  "Transaction Processing System in Hotel and Restaurant",
  "Travel Destination and Events Portal Capstone Project",
  "Property Management Information System", 
  "Hotels and Vacation Rentals",
  "Maternal Records Management",
  "Smart Healthcare Support for Remote Patient Monitoring During COVID-19 Quarantine",
  "X-Ray Results Image Archiving",
  "First Aid Knowledge-Based Mobile Application", 
  "Hospital Management System",
  "Hospital Resources and Room Utilization",
  "Online Platform for COVID-19 Contact Tracing System", 
  "Nutrition Office Management Information System",
  "Patient monitoring and tracking system of family planning in the community",
  "Mask Wearing Monitoring Application",
  "Mobile Based E-Prescribing App with Admin Panel",
  "Clinic Management System", 
  "Online Platform for Patient Dental and Medical Records",
  "Web-Based Psychopathology Diagnosis System",
  "Health and Welfare Monitoring System", 
  "Mobile Based Common Ailment Guide with Admin Panel",
  "Blood Bank Information System",
  "Medicine Reminder Application",
  "Web and Mobile Based Information of Herbal Plants and Medicinal Usages",
  "Android Based Fitness and Exercise App", 
  "Gym Management System",
  "Nutrition and Diet Mobile Application",
  "Contact Tracing Application", 
  " COVID-19 Facilities Information System",
  "Online Bus Ticket Reservation",
  "Vehicle Rental System with Mobile App Support",
  "Driving School Management System",
  "Shipping Management System",
  "Vehicle Insurance Information System",
  "GPS based Vehicle Theft Detection System using GSM Technology", 
  "Bike Portal Information System",
  "Vehicle Parking Management System",
  "Vehicle Impoundment Information Management System", 
  "Vehicle Registration Portal",
  "Vehicle Franchising and Drivers Offense Software",
  "Traffic Management System",
  "Mobile Based Airline Reservation System (Android and IOS)",
  "Tricycle Driver Conduct Reporting Mobile Application", 
  "PUV Transportation Route and Mapping System",
  "Driving School Management System",
  "QR Code Fare Payment System", 
  "Courier Management System",
  "Mobile Based Emergency Reporting with SMS Support",
  "Interactive Flood Hazard Map",
  "Web and Mobile Crime Reporting System",
  "Weather Prediction App", 
  "Bantay Baha Alert System with SMS and Push Notification",
  "Fire and Smoke Detection Application with SMS Notification",
  "SMS-based Flood Monitoring System", 
  "Crisis Information Management Software",
  "Data Platform for Emergency Response Management",
  "Fire Extinguisher and Fire Fighting Drone",
  "Disaster Management Information System",
  "Crime Scene Management Mobile Application",
  "Android Based Controlled Water Sprinkler",
  "Online Platform for Plant Calendar Scheduling", 
  "MobileMangrove a Mobile-Based Mangrove Species Field Guide",
  "Mobile Based Instructional Material for Agriculture",
  "Soil Moisture Sensor using Micro Controller", 
  "E-commerce Platform for Farm Trading Activities",
  "Web and Mobile Based Monitoring and Tracking of Fertilizer Delivery Products",
  "Online Record Archiving of Soil Analysis Results",
  "Drone Based Seeding Application Controlled by Mobile Devices",
  "Dairy Farm Management System", 
  "Water Monitoring For Aquaculture with SMS Notification",
  "Arduino Based Irrigation Device with Android Controlled Settings",
  "Android Based Feeds Scheduler Dispensing Application", 
  "Mobile Based Farm Management Application",
  "Electronic Watering System for Vegetable Nursery Garden",
  "Solar-Powered Water Filtration System used in Farm Land",
  "Curfew and Travel Pass Information System", 
  "Evacuation Center Management System", 
  "PWD Information System",
  "Cloud-Based Business Permit Processing",
  "Vaccine Distribution System", 
  "Senior Citizen Information System",
  "DSWD Donation System", 
  "Information System for Bureau of Fire Protection",
  "Poverty and Malnutrition Monitoring System", 
  "Project Monitoring and Evaluation System",  
  "BJMP’S Visitor’s Log Monitoring System",
  "City Business Permit and Monitoring System with Decision Support",
  "Barangay Records Management System", 
  "Housing Information Management with Mapping",
  "Census Monitoring", 
  "Cedula Mobile: Cedula and Certification Request Mobile Application",
  "Health Center Information Management System",
  "Online Lot Reservation",
  "Online management system",
  "Online membership and billing system",
  "Online payroll system",
  "Online POS(Point of Sale)",
  "Online Product Reservation System",
  "Online public access catalog",
  "Online shopping cart",
  "Online voting system",
  "Order Billing Inventory System",
  "Payroll system",
  "Payroll System with Biometric and Barcode Technology",
  "Pharmacy Automation System",
  "Touch-Screen Based Point-Of-Sale System (POS)",
  "Pharmacy Management System",
  "Quiz Application using Android",
  "Record management system",
  "Resort Management System",
  "RFID-Based Student Monitoring System",
  "Sales and Inventory Monitoring System with SMS",
  "Salon System",
  "School Event Attendance Monitoring System with Biometric and Barcode Technology",
  "SMS-Based Grade Inquiry System",
  "SSG Management System with SMS Notification",
  "Supply inventory system",
  "Supply inventory system",
  "Veterinary Clinic and Pet Shop Management System",
  "Video Library Management System",
  "Video Rental Application in Android",
  "Voting system",
  "Weather Forecast Application using Android",
  "Web-Based Tracking System",
  "Mobile Based Year Book Gallery App (Android and IOS)",
  "Mobile Loan Management and Inquiry Application",
  "LAN/Web Based Sales and Inventory with Decision Support System",
  "Web Application for Real Estate Record Management",
  "Android Based Doorbell Notification App with SMS Support",
  "Web and Mobile Based Faculty Evaluation System (Web for Admin and Mobile for Rating of Students)",
  "GPS based Vehicle theft detection system using GSM technology",
  "Hospital ERP System with Decision Support System: A Data Warehouse of Patient Information",
  "DTR, Payroll System with Android and SMS Notification for Employees",
  "Home Automation and Surveillance with the help of ip camera and wifi module shield",
  "ClassDroid: Web and Mobile Class Record Application",
  "Android/SMS Based Controlled Electronic Bulletin Board",
  "Nursing Education with the use of healthcare software",
  "Information Kiosk for School Campus",
  "RFid Based Security System with GSM technology",
  "Coin Operated Loading Machine Kiosk",
  "Converting Filipino Sign Language to Text using Microsoft Kinect Sensor",
  "EventScore: Web and Mobile Event Evaluation Application",
  "GSM based digital Notice board with display on PC Monitor",
  "Android Based Weather Forecast Application using OpenWeatherMap API",
  "Baha Watcher: Android Based Water Level Indicator Using Arduino with SMS Notification",
  "Air Quality Tester Application for Android (using Arduino)",
  "ItemFinder: Lost and Found Monitoring and Management System (Web and Android Application)",
  "Coin Operated Printing Kiosk",
  "Nursing education and training on management and use of healthcare software",
  "RFID Based Bus Fare Payment System",
  "Document Tagging Application with Android QR Scanner",
  "MemoDroid: Web and Mobile Memo Notification App",
  "Online Complaint Management System",
  "Online Grading and Attendance Monitoring System with SMS Notification",
  "AdviseMobile: A Web and Mobile Based Guidance Consultation System",
  "Guidance Office Centralized Information Database System",
  "Web Based Entrance Examination with Course Recommendation System (Android Support)",
  "CedulaMobile: Cedula and Brgy Certification Request and Issuance Application",
  "Mobile Health Care Management System",
  "Mobile Nutrition Application with Admin Panel (jquery mobile, php, mysql, apache cordova)",
  "Mobile Event Calendar Application",
  "Android Based Log Book Application",
  "City Tour: Mobile Based Map Application",
  "Android Based Directory Listing Application",
  "Mobile Based IQ Test Application",
  "Cross Platform Mobile Learning System",
  "Android App for Graduate School Studies",
  "Android Based Library Catalog Application",
  "RFID based Vehicle Tracking and Monitoring System",
  "SweldoMobile: Mobile Based Salary Notification App",
  "ClearDroid: Web and Android Based Clearance App",
  "Android Based Room Temperature Monitoring App",
  "Web Based Facility Management Information System",
  "Web and Mobile Based Physician Expert System",
  "Expert System in the field of Medical Technology",
  "Web Based Expense Management System with Accounting System",
  "Web and Mobile Based Web Tele Conference Application",
  "Home security System based on LPG gas, Smoke and Fire Sensors with SMS Based alertsAlumni Events Management System with SMS Notification",
  "Medical Dictionary Application (iOS, Android)",
  "RFID based Bus Announcement System for Blind",
  "Web, Mobile and SMS Based Feedback Application",
  "LAN Based Billing and Accounting System with Decision Support",
  "Advanced Vehicle Security System with Theft control and Accident Notification via Android Development",
  "Voice Recognition Application in Mobile Devices",
  "Construction Management Performance and Monitoring System",
  "Web and Mobile Based Meeting Notification App",
  "Gold Fish Guide Mobile â€“ Android Based Guide on how to take care of your Goldfish",
  "Mobile Based Course Portal",
  "RFID Door Lock Application",
  "Android Based Photography Challenge App",
  "RFID based Airport Luggage Security Scanning System",
  "Vehicle over Speed Sensing System using Arduino",
  "Crop Information Portal Using GIS Application",
  "Web Based Purchase Request Processing System",
  "Delivery Tracking System (GPS and GSM Based using Arduino)",
  "Subject Evaluator App (iOS, Android and web based)",
  "Android Based Locator Map Application",
  "Fire & Smoke Alarm System with SMS Notification",
  "Quiz Management System (mobile for students and web based for teachers)",
  "Jewelry Sales Accounting and Appraisal System",
  "Web based Manufacturing Management and Monitoring System",
  "Online Grading with Mobile Based Subject Reservation Application",
  "Warehouse Management System",
  "Human Resources Information System",
  "To Do / Checklist App",
  "RFID Enabled Passport Verification",
  "Knowledge Management System on Agriculture",
  "Multimedia Web and Mobile Application for Biology Subject",
  "Inventory Management in Android",
  "Taxi Mobile: Android Based Taxi Booking Application",
  "Android Based School Publication App",
  "Sound Memory Game",
  "Web Based School Management Integrated System",
  "Number Catch Game in Android",
  "Puzzle game in Android",
  "Agriculture Marketing Information System",
  "Android Based Water Level Controller using Arduino",
  "Contact Management Application",
  "City Guide Android Application",
  "Event Planner Mobile App",
  "Mobile Based Public Access Cataloguing",
  "Android Scheduler App",
  "Asthma Education via Mobile Application",
  "Web and Mobile Forum for Education System",
  "Poverty Heat Map using GIS Application",
  "RFID Based Livestock Tracking Application",
  "Medical Research Data Storage and Analysis System",
  "MobileMangrove: Mobile Based Mangrove Species Field Guide",
  "RescueAlert: Emergency Notification App",
  "Android Based Remote Home Monitoring System",
  "Web and Mobile Newsletter App with Forum for School Publication",
  "Monitoring of Students and Teachers with SMS Notification using RFID",
  "Role Playing Game in Unity",
  "Web Based Job Ordering with Inventory Management System",
  "Android Based Book Availability Inquiry and Reservation App",
  "Android and Online Educational Math Learning Game",
  "Flash Drive Locker with SMS Notification",
  "Feeds Scheduler Dispensing Application using Android Phone",
  "Android Based Alcohol Sensor Application",
  "Water Refilling Inventory Management System with Android Support",
  "OPOS: Online Point of Sale with Android Support",
  "Android Based Light Dimmer App using Arduino",
  "SMS based irrigation App (Android, iOS, windowMobile)",
  "Medical Research Data Storage and Analysis System",
  "Web Based Water Billing Management System with Due Date for Payment Notication via SMS",
  "Flash Flood Prediction Model using Regression Analysis with Decision Support System",
  "Web Based Customer Relations Management System",
  "Online Job Application System with Job Matching Feature",
  "E-Agriculture (geo-fencing, elearning, etc)",
  "Face Recognition with SMS notification and Security System",
  "Web Based File Manager with android app",
  "Mobile Based Airline Reservation System (Android and IOS)",
  "Mobile Based Exam Schedule Notification App",
  "Android Based Door Lock App with SMS Notification",
  "Web Based Water Billing Management System with Android and SMS Notification for Clients",
  "Web and Mobile Event Tabulation App (Web for Admin and Mobile for Judges)",
  "Android Based Attendance App using Smart Card Reader",
  "Touchscreen Point of Sale Application",
  "Cloud Based Accounting Application for Business Analytics",
]

function newTitle() {
	var randomTitles = Math.floor(Math.random() * (researchTitles.length));
	document.getElementById('answer').innerHTML = researchTitles[randomTitles];
	document.getElementById('answer').style.background = "#EAE3D2";
  document.getElementById('answer').style.color = "#000";
}
